theme: jekyll-theme-hacker
title: Sergi4UA Blog
description: Games'n'Blog
show_downloads: false
author: Sergi4UA
url: https://sergi4ua.github.io
webmaster_verifications:
  google: MeT4zIGmwwM3862vUI4MyGBw3GRk0KJFLRlHbMup12s
plugins:
  - jekyll-seo-tag
  - jekyll-sitemap